/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: 3DRT STUDIOS (https://sketchfab.com/Hanako.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-brain-7a27c17fd6c0488bb31ab093236a47fb
Title: Human Brain
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useState } from "react";
import { useEffect } from "react";
import * as THREE from "three";

export function Brain(props) {
  const { nodes, materials } = useGLTF("/brain/scene.gltf");
  const [material, setMaterial] = useState(materials.material_0)
  

  useEffect(() => {
    const color = {...material.color,  r: 247, g: 120, b: 1 }
    const MeshStandardMaterial  = {...material, color}
    console.log(material);
    console.log(MeshStandardMaterial );
    // setMaterial({MeshStandardMaterial });
   
  },[] )

  const texture = useTexture('/brain/textures/Brain_Matter_001_COLOR.jpg')
  const leatherTextureProps = useTexture({
    // map: "./textures/leather/Leather_008_Base Color.jpg",
    normalMap: "/brain/textures/material_0_diffuse.png",
    roughnessMap: "/brain/textures/material_0_diffuse.png",
    aoMap: "/brain/textures/material_0_diffuse.png",
  });

  // leatherTextureProps.map.repeat.set(3, 3);
  // leatherTextureProps.normalMap.repeat.set(3, 3);
  // leatherTextureProps.roughnessMap.repeat.set(3, 3);
  // leatherTextureProps.aoMap.repeat.set(3, 3);
  // leatherTextureProps.map.wrapS = leatherTextureProps.map.wrapT =
  //   THREE.MirroredRepeatWrapping;
  
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        // material={material}
        scale={0.1}
        position={0}
        
      >
        <meshStandardMaterial  map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/brain/scene.gltf");
