/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 digestive_system.glb
Author: b.boukhari5d (https://sketchfab.com/b.boukhari5d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/digestive-system-f78ce703805f49d3b732e37be5b93188
Title: digestive system
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/brain/digestive_system.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.05} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="digestive_systemFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="DigestiveSystem001" position={[0, 24.04, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_7" position={[-0.2, -7.93, -126.91]}>
                    <mesh name="DigestiveSystem001_Digestive_System_0" geometry={nodes.DigestiveSystem001_Digestive_System_0.geometry} material={materials.Digestive_System} />
                  </group>
                </group>
                <group name="��������" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="������������" rotation={[-Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/brain/digestive_system.glb')
