/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 human_brain.glb
Author: 3DRT STUDIOS (https://sketchfab.com/Hanako.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-brain-7a27c17fd6c0488bb31ab093236a47fb
Title: Human Brain
*/

import React, { useRef } from "react";
import { MeshDistortMaterial, useGLTF, useTexture } from "@react-three/drei";

export function Model(props) {
  const texture = useTexture("/brain/textures/material_0_diffuse1.png");

  // texture.repeat.set(0.5, 1);
  const { nodes, materials } = useGLTF("/brain/human_brain.glb");
  console.log(nodes, materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
        scale={0.1}
        
      >
        {/* <boxGeometry attach="geometry" args={[0.01, 0.01, 0.01]} /> */}
        <meshStandardMaterial geometry={nodes.Object_5.geometry} map={texture} aoMap={texture} attach="material" />
       
      </mesh>
    </group>
  );
}

useGLTF.preload("/brain/human_brain.glb");
