/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: 3DRT STUDIOS (https://sketchfab.com/Hanako.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-brain-7a27c17fd6c0488bb31ab093236a47fb
Title: Human Brain
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain/scene.gltf')
  const texture = useTexture("/brain/textures/Brain_Matter_001_COLOR.jpg");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} position={0} material={materials.material_0} scale={0.1} >

      <meshStandardMaterial map={texture}  />
      </mesh>
    </group>
  )
}

useGLTF.preload('/brain/scene.gltf')
